[project]
name = "con-tribute"
version = "0.1.0"
description = "play with your github contribution graph"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "requests>=2.32.4",
]
